style = "sciml"
indent = 2
margin = 92
always_use_return = false
short_to_long_function_def = false
annotate_untyped_fields_with_any = false
whitespace_typedefs = false
whitespace_ops_in_indices = false
whitespace_in_kwargs = false
separate_kwargs_with_semicolon = false
